# Based on info from http://archive.is/eHtSi
# Digital Ocean guide on OpenVPN
#
---
- hosts: all
  become: true
  roles:
  - Stouts.openvpn
  vars:
    openvpn_enabled: false

  tasks:
  - debug: msg="This is where the OpenVPN set up tasks will go"
