# Based on info from http://archive.is/eHtSi
# Digital Ocean guide on OpenVPN
#
---
- hosts: all
  gather_facts: false
  become: true

  tasks:
  - name: Update APT Package cache
    apt: update_cache=yes cache_valid_time=3600
  - name: Install software
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - openvpn
      - easy-rsa
